Update chisel-wrapper, run shellcheck

diff --git a/chisel-wrapper b/chisel-wrapper
--- a/chisel-wrapper
+++ b/chisel-wrapper
@@ -10,28 +10,21 @@
 #   CHISEL_CACHE_DIR          (optional) the path which chisel will use to store it's cache
 #   CHISEL_DPKG_STATUS_FILE   (required) the path where the dpkg status file should be generated
 
-set -e
+set -eu
 
-CHISEL_BIN="${CHISEL_BIN:-"./chisel"}"
-CHISEL_CACHE_DIR="${CHISEL_CACHE_DIR:-".chisel-cache"}"
-CHISEL_DPKG_STATUS_FILE="${CHISEL_DPKG_STATUS_FILE}"
+CHISEL_BIN="${CHISEL_BIN:-"chisel"}"
+CHISEL_CACHE_DIR="${CHISEL_CACHE_DIR:-"$(mktemp -d)"}"
 
 _print_error() {
-	echo "Error: $@" >> /dev/stderr
-}
-
-_cleanup_cache() {
-	if [ -d "${CHISEL_CACHE_DIR}" ]; then
-		rm -rf "${CHISEL_CACHE_DIR}"
-	fi
+	echo "Error:" "$@" >> /dev/stderr
 }
 
 _install_slices() {
-	XDG_CACHE_HOME="${CHISEL_CACHE_DIR}" ${CHISEL_BIN} cut "$@"
+	XDG_CACHE_HOME="$CHISEL_CACHE_DIR" $CHISEL_BIN cut "$@"
 }
 
 _prepare_dpkg_status() {
-	local dir="${CHISEL_CACHE_DIR}/chisel/sha256"
+	dir="$CHISEL_CACHE_DIR/chisel/sha256"
 	if [ ! -d "$dir" ]; then
 		_print_error "could not find the chisel cache at ${dir}"
 		exit 1
@@ -42,12 +35,12 @@ _prepare_dpkg_status() {
 	fi
 
 	for f in "$dir"/*; do
-		local is_deb="$(file "$f" | grep "Debian binary package" | cat)"
+		is_deb="$(file "$f" | grep "Debian binary package" | cat)"
 		if [ -z "$is_deb" ]; then
 			continue
 		fi
-		dpkg-deb -f "$f" >> "${CHISEL_DPKG_STATUS_FILE}"
-		echo "" >> "${CHISEL_DPKG_STATUS_FILE}"
+		dpkg-deb -f "$f" >> "$CHISEL_DPKG_STATUS_FILE"
+		echo "" >> "$CHISEL_DPKG_STATUS_FILE"
 	done
 }
 
@@ -56,7 +49,5 @@ if [ -z "$CHISEL_DPKG_STATUS_FILE" ] ; then
 	exit 1
 fi
 
-_cleanup_cache
 _install_slices "$@"
 _prepare_dpkg_status
-_cleanup_cache
